### ISSUE TITLE
stream_until_token() has an unknown bug, sometimes missing the token

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/formdata#10]
I think it is happening when the buffer drains and refills, but I'm not sure yet.
I'm working on it.

**Comment by mikedilger** [comment]
After a lot of testing, it appears this is actually bug #1

The buffer gets smaller and smaller as we parse bits off of it, and eventually it very well could be shorter than the size of the token.   Closing in favour of #1

**Comment by alanstockwell** [comment]
Thank god! _peasant rejoicing_
