### ISSUE TITLE
Add support for multidata/formdata to servo/servo

### ISSUE THREAD

**Issue by psdh** [mikedilger/formdata#17]
@mikedilger We were wanting to add formdata support for Servo(servo/servo#7553). I went through the repository but couldn't confirm if this parser conforms to any spec. It'd be great if you could help us in this regard.

**Comment by mikedilger** [comment]
I'll respond to this over at servo/servo#7553 and leave this open for further discussion on what this library might need to support servo

**Comment by mikedilger** [comment]
Closing as upstream issue https://github.com/servo/servo/issues/7553 has been addressed.
