### ISSUE TITLE
Iron Plugin

### ISSUE THREAD

**Issue by mcasper** [mikedilger/formdata#18]
Have you considered or would you be open to making this an Iron plugin? It seems like one of the major use cases for this would be with an Iron app, and it would be great to be able to do something like

``` Rust
fn handle(&self, req: &mut Request) -> IronResult {
  let form_data = req.get_ref::<FormData>();
  // etc
}
```

Whether the plugin code be in this repo or another that depends on this, Iron doesn't have any official multipart/form-data support yet that I've found, and it would be awesome to see this as a plugin. (Coming from someone writing an app that's going to deal with lots of file uploading)

**Comment by mikedilger** [comment]
This has come up before (#13), and I made changes (92ff81ea12915bd1cd1b8f71ccddcb5b849540b3) to support this.

The `params` crate at https://crates.io/crates/params is the Iron plugin you are looking for.

**Comment by mcasper** [comment]
Thanks!
