### ISSUE TITLE
Build failed for Rust 1.11.0

### ISSUE THREAD

**Issue by mrLSD** [mikedilger/formdata#34]
rustc 1.11.0 (9b21dcd6a 2016-08-15)
cargo 0.12.0-nightly (6b98d1f 2016-07-04)

Message:

>    Compiling textnonce v0.3.4
> /home/evgeny/.cargo/registry/src/github.com-1ecc6299db9ec823/formdata-0.8.4/build.rs:20:35: 20:48 error: mismatched types [E0308]
> /home/evgeny/.cargo/registry/src/github.com-1ecc6299db9ec823/formdata-0.8.4/build.rs:20         ::serde_codegen::register(&mut registry);
>                                                                                                                           ^~~~~~~~~~~~~
> /home/evgeny/.cargo/registry/src/github.com-1ecc6299db9ec823/formdata-0.8.4/build.rs:20:35: 20:48 help: run `rustc --explain E0308` to see a detailed explanation
> /home/evgeny/.cargo/registry/src/github.com-1ecc6299db9ec823/formdata-0.8.4/build.rs:20:35: 20:48 note: expected type `&mut syntex::Registry`
> /home/evgeny/.cargo/registry/src/github.com-1ecc6299db9ec823/formdata-0.8.4/build.rs:20:35: 20:48 note:    found type `&mut syntex::Registry`
> /home/evgeny/.cargo/registry/src/github.com-1ecc6299db9ec823/formdata-0.8.4/build.rs:20:35: 20:48 note: Perhaps two different versions of crate `syntex` are being used?
> /home/evgeny/.cargo/registry/src/github.com-1ecc6299db9ec823/formdata-0.8.4/build.rs:20         ::serde_codegen::register(&mut registry);
>                                                                                                                           ^~~~~~~~~~~~~
> /home/evgeny/.cargo/registry/src/github.com-1ecc6299db9ec823/textnonce-0.3.4/build.rs:20:35: 20:48 error: mismatched types [E0308]
> /home/evgeny/.cargo/registry/src/github.com-1ecc6299db9ec823/textnonce-0.3.4/build.rs:20         ::serde_codegen::register(&mut registry);
>                                                                                                                            ^~~~~~~~~~~~~
> /home/evgeny/.cargo/registry/src/github.com-1ecc6299db9ec823/textnonce-0.3.4/build.rs:20:35: 20:48 help: run `rustc --explain E0308` to see a detailed explanation
> /home/evgeny/.cargo/registry/src/github.com-1ecc6299db9ec823/textnonce-0.3.4/build.rs:20:35: 20:48 note: expected type `&mut syntex::Registry`
> /home/evgeny/.cargo/registry/src/github.com-1ecc6299db9ec823/textnonce-0.3.4/build.rs:20:35: 20:48 note:    found type `&mut syntex::Registry`
> /home/evgeny/.cargo/registry/src/github.com-1ecc6299db9ec823/textnonce-0.3.4/build.rs:20:35: 20:48 note: Perhaps two different versions of crate `syntex` are being used?
> /home/evgeny/.cargo/registry/src/github.com-1ecc6299db9ec823/textnonce-0.3.4/build.rs:20         ::serde_codegen::register(&mut registry);
>                                                                                                                            ^~~~~~~~~~~~~
> error: aborting due to previous error
> error: aborting due to previous error
> Build failed, waiting for other jobs to finish...
> error: Could not compile `textnonce`.

**Comment by mikedilger** [comment]
Look like you are using a 0.8.x version of formdata.  The lastest is the 0.9.x branch.   0.8 is okay but it had a lot of problems like the one above, mostly related to serde, different rust versions, nightly vs. stable, and cargo not being able to synchronize dependencies.  I eventually gave up and removed serde support when 0.9 was released.   I'll add back serde support once the AST is stable and syntax extensions are stable.

If you can't upgrade to 0.9 or if you need serde support, you'll need to fiddle with your Cargo.lock file.  Figure out why "two different versions of crate syntex are being used", and force the versions to match up.  Commands like "cargo update -p `package` --precise `version`" can help.
