### ISSUE TITLE
Release a version supporting Hyper 0.10

### ISSUE THREAD

**Issue by golddranks** [mikedilger/formdata#36]
Release a version supporting Hyper 0.10. I'll see if that's an quick thing enough to do, I'll send a PR.

**Comment by golddranks** [comment]
Okay, seems unproblematic, but since this publicly depends on `mime-multipart`, that needs to be updated too. I sent a PR to mime-multipart.

**Comment by mikedilger** [comment]
I've merged your mime-multipart changes, and just published.  If you send me a PR for this I'll merge it, otherwise I'll do it later tonight.

**Comment by mikedilger** [comment]
oh that was easier than I thought.  incoming...

**Comment by golddranks** [comment]
Thanks a lot!
